# Generated by Django 5.1.4 on 2025-03-16 16:10

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("challenge_id", models.CharField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Upcoming", "Upcoming"),
                            ("Currently Running", "Currently Running"),
                            ("Archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("icon", models.CharField(blank=True, max_length=20, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "example_proof_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="When the prediction was created in DB",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
                "db_table": "challenges",
            },
        ),
    ]
