# Generated by Django 5.1.4 on 2025-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("UPCOMING", "UPCOMING"),
                    ("ONGOING", "ONGOING"),
                    ("COMPLETED", "COMPLETED"),
                ],
                help_text="Read-only. Calculated based on is_published, start_date and end_date.",
                max_length=20,
            ),
        ),
    ]
