# Generated by Django 5.1.7 on 2025-04-20 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_challenge_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="status",
        ),
    ]
