# Generated by Django 5.1.7 on 2025-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_remove_challenge_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="stats",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
