# Generated by Django 5.1.7 on 2025-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0004_challenge_stats"),
        ("locations", "0007_alter_location_osm_brand_and_osm_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="locations",
            field=models.ManyToManyField(blank=True, to="locations.location"),
        ),
    ]
