# Generated by Django 5.2.11 on 2026-04-12 08:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_challenge_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="categories_full",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                help_text="Full category tags with parents, used for matching & stats (read-only)",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                help_text="Restrict to one or multiple categories (optional)",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict to one or multiple locations (optional)",
                related_name="challenges",
                to="locations.location",
            ),
        ),
    ]
