# Generated by Django 5.2.17 on 2026-09-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0006_challenge_categories_full"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="promo_banner_alt_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="promo_banner_image_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="promo_banner_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
