METRIC_PRICE_COUNT = "price_count"
METRIC_PRICE_IN_PROOF_NOT_OWNED_COUNT = "price_in_proof_not_owned_count"
METRIC_PROOF_COUNT = "proof_count"
METRIC_PROOF_PRICE_TAG_COUNT = "proof_type_price_tag_count"
METRIC_PROOF_RECEIPT_COUNT = "proof_type_receipt_count"
METRIC_PROOF_GDPR_REQUEST_COUNT = "proof_type_gdpr_request_count"
METRIC_PROOF_SHOP_IMPORT_COUNT = "proof_type_shop_import_count"
METRIC_LOCATION_COUNT = "location_count"
METRIC_LOCATION_CITY_COUNT = "location_type_osm_city_count"
METRIC_LOCATION_COUNTRY_COUNT = "location_type_osm_country_count"
METRIC_CURRENCY_COUNT = "currency_count"
METRIC_YEAR_COUNT = "year_count"
METRIC_CHALLENGE_COUNT = "challenge_count"

METRIC_LIST = [
    METRIC_PRICE_COUNT,
    METRIC_PRICE_IN_PROOF_NOT_OWNED_COUNT,
    METRIC_PROOF_COUNT,
    METRIC_PROOF_PRICE_TAG_COUNT,
    METRIC_PROOF_RECEIPT_COUNT,
    METRIC_PROOF_GDPR_REQUEST_COUNT,
    METRIC_PROOF_SHOP_IMPORT_COUNT,
    METRIC_LOCATION_COUNT,
    METRIC_LOCATION_CITY_COUNT,
    METRIC_LOCATION_COUNTRY_COUNT,
    METRIC_CURRENCY_COUNT,
    METRIC_YEAR_COUNT,
    METRIC_CHALLENGE_COUNT,
]
METRIC_CHOICES = [(key, key) for key in METRIC_LIST]
