import enum


class Unit(enum.StrEnum):
    KILOGRAM = "KILOGRAM"
    LITER = "LITER"
    UNIT = "UNIT"


class DiscountType(enum.StrEnum):
    QUANTITY = "QUANTITY"  # example: buy 1 get 1 free
    SALE = "SALE"  # example: 50% off
    SEASONAL = "SEASONAL"  # example: Christmas sale
    LOYALTY_PROGRAM = "LOYALTY_PROGRAM"  # example: 10% off for members
    EXPIRES_SOON = "EXPIRES_SOON"  # example: 30% off expiring soon
    PICK_IT_YOURSELF = "PICK_IT_YOURSELF"  # example: 5% off for pick-up
    SECOND_HAND = "SECOND_HAND"  # example: second hand books or clothes
    OTHER = "OTHER"
    NO_DISCOUNT = "NO_DISCOUNT"  # no discount applied


class RawCategory(enum.StrEnum):
    APPLES = "en:apples"
    APRICOTS = "en:apricots"
    ARTICHOKES = "en:artichokes"
    ASPARAGUS = "en:asparagus"
    AUBERGINES = "en:aubergines"
    AVOCADOS = "en:avocados"
    BANANAS = "en:bananas"
    BEETROOT = "en:beetroot"
    BERRIES = "en:berries"
    BLACKBERRIES = "en:blackberries"
    BLUEBERRIES = "en:blueberries"
    BOK_CHOY = "en:bok-choy"
    BROCCOLI = "en:broccoli"
    CABBAGES = "en:cabbages"
    CARROTS = "en:carrots"
    CAULIFLOWERS = "en:cauliflowers"
    CELERY = "en:celery"
    CELERIAC = "en:celeriac"
    CELERY_STALK = "en:celery-stalk"
    CEP_MUSHROOMS = "en:cep-mushrooms"
    CHANTERELLES = "en:chanterelles"
    CHARDS = "en:chards"
    CHERRIES = "en:cherries"
    CHERRY_TOMATOES = "en:cherry-tomatoes"
    CHICKPEAS = "en:chickpeas"
    CHIVES = "en:chives"
    CLEMENTINES = "en:clementines"
    COCONUTS = "en:coconuts"
    CRANBERRIES = "en:cranberries"
    CUCUMBERS = "en:cucumbers"
    DATES = "en:dates"
    ENDIVES = "en:endives"
    FENNEL_BULBS = "en:fennel-bulbs"
    FIGS = "en:figs"
    GARLIC = "en:garlic"
    GINGER = "en:ginger"
    GRAPEFRUITS = "en:grapefruits"
    GRAPES = "en:grapes"
    GREEN_BEANS = "en:green-beans"
    GREEN_SWEET_PEPPERS = "en:green-sweet-peppers"
    KIWIS = "en:kiwis"
    KAKIS = "en:kakis"
    LEEKS = "en:leeks"
    LEMONS = "en:lemons"
    LETTUCES = "en:lettuces"
    LIMES = "en:limes"
    LYCHEES = "en:lychees"
    MANDARIN_ORANGES = "en:mandarin-oranges"
    MANGOES = "en:mangoes"
    MELONS = "en:melons"
    MUSHROOMS = "en:mushrooms"
    NECTARINES = "en:nectarines"
    ONIONS = "en:onions"
    ORANGES = "en:oranges"
    PAPAYAS = "en:papayas"
    PARSNIP = "en:parsnip"
    PASSION_FRUITS = "en:passion-fruits"
    PEACHES = "en:peaches"
    PEARS = "en:pears"
    PEAS = "en:peas"
    PEPPERS = "en:peppers"
    PINEAPPLE = "en:pineapple"
    PLUMS = "en:plums"
    POMEGRANATES = "en:pomegranates"
    POMELOS = "en:pomelos"
    POTATOES = "en:potatoes"
    PUMPKINS = "en:pumpkins"
    RADISHES = "en:radishes"
    RASPBERRIES = "en:raspberries"
    RED_BELL_PEPPERS = "en:red-bell-peppers"
    RED_ONIONS = "en:red-onions"
    RHUBARBS = "en:rhubarbs"
    SCALLIONS = "en:scallions"
    SHALLOTS = "en:shallots"
    SPINACHS = "en:spinachs"
    SPROUTS = "en:sprouts"
    STRAWBERRIES = "en:strawberries"
    TOMATOES = "en:tomatoes"
    TURNIP = "en:turnip"
    WATERMELONS = "en:watermelons"
    WALNUTS = "en:walnuts"
    YELLOW_ONIONS = "en:yellow-onions"
    ZUCCHINI = "en:zucchini"
    OTHER = "other"
