# Where to find documentation
docs_dir: docs

# Link to Github on every page
repo_url: https://github.com/openfoodfacts/open-prices
edit_uri: blob/main/docs/

site_name: Open Prices
site_dir: gh_pages

theme:
  name: material

markdown_extensions:
  - footnotes
  - mdx_truly_sane_lists
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - awesome-pages
  - search
