# Generated by Django 5.2.14 on 2026-06-20 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("price_count", "price_count"),
                            ("proof_count", "proof_count"),
                            ("location_count", "location_count"),
                            (
                                "location_type_osm_country_count",
                                "location_type_osm_country_count",
                            ),
                            ("year_count", "year_count"),
                            ("challenge_count", "challenge_count"),
                        ],
                        max_length=40,
                    ),
                ),
                ("threshold", models.PositiveIntegerField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("user_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
    ]
