# Generated by Django 5.2.14 on 2026-08-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0002_userbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="metric",
            field=models.CharField(
                choices=[
                    ("price_count", "price_count"),
                    (
                        "price_in_proof_not_owned_count",
                        "price_in_proof_not_owned_count",
                    ),
                    ("proof_count", "proof_count"),
                    ("proof_type_price_tag_count", "proof_type_price_tag_count"),
                    ("proof_type_receipt_count", "proof_type_receipt_count"),
                    ("proof_type_gdpr_request_count", "proof_type_gdpr_request_count"),
                    ("proof_type_shop_import_count", "proof_type_shop_import_count"),
                    ("location_count", "location_count"),
                    ("location_type_osm_city_count", "location_type_osm_city_count"),
                    (
                        "location_type_osm_country_count",
                        "location_type_osm_country_count",
                    ),
                    ("currency_count", "currency_count"),
                    ("year_count", "year_count"),
                    ("challenge_count", "challenge_count"),
                ],
                max_length=40,
            ),
        ),
    ]
