# Generated by Django 5.1 on 2024-10-18 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0002_alter_price_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="receipt_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Receipt's price quantity (user input)",
            ),
        ),
    ]
