# Generated by Django 5.1.4 on 2025-01-01 22:11

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_price_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="receipt_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Receipt's price quantity (user input)",
            ),
        ),
    ]
