# Generated by Django 5.1.4 on 2025-02-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0005_alter_price_receipt_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QUANTITY", "QUANTITY"),
                    ("PROMOTION", "PROMOTION"),
                    ("SEASONAL", "SEASONAL"),
                    ("LOYALTY_PROGRAM", "LOYALTY_PROGRAM"),
                    ("EXPIRES_SOON", "EXPIRES_SOON"),
                    ("PICK_IT_YOURSELF", "PICK_IT_YOURSELF"),
                    ("OTHER", "OTHER"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="price_is_discounted",
            field=models.BooleanField(default=False),
        ),
    ]
