# Generated by Django 5.1.4 on 2025-02-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0006_price_discount_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QUANTITY", "QUANTITY"),
                    ("SALE", "SALE"),
                    ("SEASONAL", "SEASONAL"),
                    ("LOYALTY_PROGRAM", "LOYALTY_PROGRAM"),
                    ("EXPIRES_SOON", "EXPIRES_SOON"),
                    ("PICK_IT_YOURSELF", "PICK_IT_YOURSELF"),
                    ("SECOND_HAND", "SECOND_HAND"),
                    ("OTHER", "OTHER"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
