# Generated by Django 5.1.4 on 2025-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0007_alter_price_discount_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="owner_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
