# Generated by Django 5.1.7 on 2025-04-10 16:10

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0008_price_owner_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="receipt_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Receipt's price quantity (user input)",
            ),
        ),
    ]
