# Generated by Django 5.1.7 on 2025-04-26 20:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0009_alter_price_receipt_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
    ]
