# Generated by Django 5.1.7 on 2025-09-16 20:48

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_labels_tags_data(apps, schema_editor):
    Price = apps.get_model("prices", "Price")
    for price in Price.objects.exclude(labels_tags=None).exclude(
        labels_tags__isnull=True
    ):
        if price.labels_tags:
            price.labels_tags_temp = price.labels_tags
            price.save(update_fields=["labels_tags_temp"])


def migrate_origins_tags_data(apps, schema_editor):
    Price = apps.get_model("prices", "Price")
    for price in Price.objects.exclude(origins_tags=None).exclude(
        origins_tags__isnull=True
    ):
        if price.origins_tags:
            price.origins_tags_temp = price.origins_tags
            price.save(update_fields=["origins_tags_temp"])


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("prices", "0011_alter_price_price_alter_price_price_without_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="labels_tags_temp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="origins_tags_temp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, null=True, size=None
            ),
        ),
        migrations.RunPython(
            migrate_labels_tags_data,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
        migrations.RunPython(
            migrate_origins_tags_data,
            reverse_code=migrations.RunPython.noop,
            atomic=True,
        ),
        migrations.RemoveField(model_name="price", name="labels_tags"),
        migrations.RemoveField(model_name="price", name="origins_tags"),
        migrations.RenameField(
            model_name="price", old_name="labels_tags_temp", new_name="labels_tags"
        ),
        migrations.RenameField(
            model_name="price", old_name="origins_tags_temp", new_name="origins_tags"
        ),
    ]
