# Generated by Django 5.1.13 on 2026-01-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0013_historicalprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprice",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="prices.price",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="prices.price",
            ),
        ),
    ]
