# Generated by Django 5.2.10 on 2026-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0015_alter_historicalprice_currency_alter_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='owner',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='owner',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
