# Generated by Django 5.2.10 on 2026-02-22 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0016_alter_historicalprice_owner_alter_price_owner"),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE MATERIALIZED VIEW price_statistics_5y AS (
              SELECT
                t2.osm_address_country_code || '_' || t1.product_code || '_' || t1.price_per || '_' || t1.currency as id,
                t2.osm_address_country_code,
                t1.product_code as code,
                t1.price_per,
                t1.currency,
                'PRODUCT' as type,
                AVG(price) as mean,
                COUNT(*) as count,
                STDDEV(price) as stddev,
                MIN(price) as min,
                MAX(price) as max,
                PERCENTILE_CONT(0.5) WITHIN GROUP (
                  ORDER BY
                    price
                ) as median
              FROM
                prices as t1
                JOIN locations as t2 on t1.location_id = t2.id
              WHERE
                t1.type = 'PRODUCT'
                AND t1.date >= CURRENT_DATE - (interval '5 years')
              GROUP BY
                t2.osm_address_country_code,
                t1.product_code,
                t1.price_per,
                t1.currency
            )
            UNION
            (
              SELECT
                t2.osm_address_country_code || '_' || t1.category_tag || '_' || t1.price_per || '_' || t1.currency as id,
                t2.osm_address_country_code,
                t1.category_tag as code,
                t1.price_per,
                t1.currency,
                'CATEGORY' as type,
                AVG(price) as mean,
                COUNT(*) as count,
                STDDEV(price) as stddev,
                MIN(price) as min,
                MAX(price) as max,
                PERCENTILE_CONT(0.5) WITHIN GROUP (
                  ORDER BY
                    price
                ) as median
              FROM
                prices as t1
                JOIN locations as t2 on t1.location_id = t2.id
              WHERE
                t1.type = 'CATEGORY'
                AND t1.date >= CURRENT_DATE - (interval '5 years')
              GROUP BY
                t2.osm_address_country_code,
                t1.category_tag,
                t1.price_per,
                t1.currency
            );
            """,
            reverse_sql="DROP MATERIALIZED VIEW price_statistics_5y;",
        )
    ]
