"""Add product brands field

Revision ID: 1e60d73e79cd
Revises: 727cb6912bd5
Create Date: 2023-12-18 15:53:40.553628

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e60d73e79cd"
down_revision: Union[str, None] = "727cb6912bd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("brands", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "brands")
    # ### end Alembic commands ###
