"""Add Price.location relationship

Revision ID: 1c8431a64d3a
Revises: b3b951e016d0
Create Date: 2023-11-16 15:59:03.881443

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c8431a64d3a"
down_revision: Union[str, None] = "b3b951e016d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("location_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "prices", "locations", ["location_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prices", type_="foreignkey")
    op.drop_column("prices", "location_id")
    # ### end Alembic commands ###
