"""Add Price.product relationship

Revision ID: 7103fb49908f
Revises: df15f7cacf48
Create Date: 2023-11-21 20:13:21.521496

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7103fb49908f"
down_revision: Union[str, None] = "df15f7cacf48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("product_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "prices", "products", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prices", type_="foreignkey")
    op.drop_column("prices", "product_id")
    # ### end Alembic commands ###
