"""Create Location table

Revision ID: b3b951e016d0
Revises: 20145023aad0
Create Date: 2023-11-16 14:32:39.734937

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3b951e016d0"
down_revision: Union[str, None] = "20145023aad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("osm_id", sa.BigInteger(), nullable=True),
        sa.Column("osm_type", sa.String(length=255), nullable=True),
        sa.Column("osm_display_name", sa.String(), nullable=True),
        sa.Column("osm_lat", sa.Numeric(precision=11, scale=7), nullable=True),
        sa.Column("osm_lon", sa.Numeric(precision=11, scale=7), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_id"), "locations", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_id"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
