"""Add proof price_count field

Revision ID: 1cf89b834379
Revises: f3c157567667
Create Date: 2024-02-04 16:32:07.827619

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cf89b834379"
down_revision: Union[str, None] = "f3c157567667"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proofs",
        sa.Column("price_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_index(
        op.f("ix_proofs_price_count"), "proofs", ["price_count"], unique=False
    )
    # Set the price_count to the number of prices for each proof
    op.execute(
        """
        UPDATE proofs
        SET price_count = (
            SELECT COUNT(*)
            FROM prices
            WHERE prices.proof_id = proofs.id
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proofs_price_count"), table_name="proofs")
    op.drop_column("proofs", "price_count")
    # ### end Alembic commands ###
