"""Add location price_count field

Revision ID: 13bb81a35e60
Revises: 314feff3af1e
Create Date: 2024-01-14 09:01:38.460521

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13bb81a35e60"
down_revision: Union[str, None] = "314feff3af1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column("price_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_index(
        op.f("ix_locations_price_count"), "locations", ["price_count"], unique=False
    )
    # Set the price_count to the number of prices for each location
    op.execute(
        """
        UPDATE locations
        SET price_count = (
            SELECT COUNT(*)
            FROM prices
            WHERE prices.location_id = locations.id
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_price_count"), table_name="locations")
    op.drop_column("locations", "price_count")
    # ### end Alembic commands ###
