"""add_index_on_product_price_count

Revision ID: 314feff3af1e
Revises: fffca9fb2990
Create Date: 2024-01-11 10:51:11.343738

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "314feff3af1e"
down_revision: Union[str, None] = "fffca9fb2990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_products_price_count"), "products", ["price_count"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_price_count"), table_name="products")
    # ### end Alembic commands ###
