"""Add Product brands_tags field

Revision ID: d2d14a95ae1c
Revises: 76d67467ff32
Create Date: 2024-02-15 11:24:20.984844

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2d14a95ae1c"
down_revision: Union[str, None] = "76d67467ff32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "brands_tags",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_products_brands_tags"), "products", ["brands_tags"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_brands_tags"), table_name="products")
    op.drop_column("products", "brands_tags")
    # ### end Alembic commands ###
