"""add proof.is_public field

Revision ID: 007443669adc
Revises: 1bf4306fff2f
Create Date: 2024-01-10 15:08:57.569316

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007443669adc"
down_revision: Union[str, None] = "1bf4306fff2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proofs",
        sa.Column("is_public", sa.Boolean(), server_default="true", nullable=False),
    )
    op.create_index(op.f("ix_proofs_is_public"), "proofs", ["is_public"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proofs_is_public"), table_name="proofs")
    op.drop_column("proofs", "is_public")
    # ### end Alembic commands ###
