"""Add Product source_last_synced field

Revision ID: 77331afdcd8e
Revises: 295d1735cc72
Create Date: 2024-03-17 23:58:25.525085

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77331afdcd8e"
down_revision: Union[str, None] = "295d1735cc72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("source_last_synced", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "source_last_synced")
    # ### end Alembic commands ###
