"""Add price price_is_discounted field

Revision ID: f3c157567667
Revises: 3c2015517236
Create Date: 2024-01-25 10:04:31.409392

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3c157567667"
down_revision: Union[str, None] = "3c2015517236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prices",
        sa.Column(
            "price_is_discounted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # Set the price_is_discounted for existing prices
    op.execute(
        """
        UPDATE prices
        SET price_is_discounted = true
        WHERE price_without_discount IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "price_is_discounted")
    # ### end Alembic commands ###
