"""Add Proof currency field

Revision ID: 49a828f10b05
Revises: 5f5835d81917
Create Date: 2024-06-19 15:36:55.542647

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49a828f10b05"
down_revision: Union[str, None] = "5f5835d81917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proofs", sa.Column("currency", sa.String(length=3), nullable=True))
    # Set the currency to the currency of the first price for each proof
    op.execute(
        """
        UPDATE proofs
        SET currency = (
            SELECT currency
            FROM prices
            WHERE prices.proof_id = proofs.id
            LIMIT 1
        )
        WHERE type IN ('PRICE_TAG', 'RECEIPT')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proofs", "currency")
    # ### end Alembic commands ###
