"""Add Proof source field

Revision ID: 8ec02f1af257
Revises: 8a6892a20b5d
Create Date: 2024-06-04 12:15:04.418674

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ec02f1af257"
down_revision: Union[str, None] = "8a6892a20b5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proofs", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proofs", "source")
    # ### end Alembic commands ###
