"""Add user price_count field

Revision ID: 868640c5012e
Revises: 13bb81a35e60
Create Date: 2024-01-14 13:26:10.269120

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "868640c5012e"
down_revision: Union[str, None] = "13bb81a35e60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("price_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_index(
        op.f("ix_users_price_count"), "users", ["price_count"], unique=False
    )
    # Set the price_count to the number of prices for each user
    op.execute(
        """
        UPDATE users
        SET price_count = (
            SELECT COUNT(*)
            FROM prices
            WHERE prices.owner = users.user_id
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_price_count"), table_name="users")
    op.drop_column("users", "price_count")
    # ### end Alembic commands ###
