"""add product.unique_scans_n column

Revision ID: 3f8d293e669e
Revises: 24d71d56d493
Create Date: 2024-01-05 09:23:21.726450

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f8d293e669e"
down_revision: Union[str, None] = "24d71d56d493"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("unique_scans_n", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "unique_scans_n")
    # ### end Alembic commands ###
