"""set unique_scans_n default to 0

Revision ID: 1bf4306fff2f
Revises: 3f8d293e669e
Create Date: 2024-01-09 13:30:47.327891

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bf4306fff2f"
down_revision: Union[str, None] = "3f8d293e669e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE products SET unique_scans_n = 0 WHERE unique_scans_n IS NULL;")
    op.alter_column(
        "products",
        "unique_scans_n",
        existing_type=sa.INTEGER(),
        nullable=False,
        server_default="0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "unique_scans_n",
        existing_type=sa.INTEGER(),
        nullable=True,
        server_default=None,
    )
    # ### end Alembic commands ###
