"""Add Product nova_group field

Revision ID: 295d1735cc72
Revises: 7055fe5b4775
Create Date: 2024-03-14 10:43:59.204833

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "295d1735cc72"
down_revision: Union[str, None] = "7055fe5b4775"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("nova_group", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "nova_group")
    # ### end Alembic commands ###
