"""Remove proof.is_public flag

Revision ID: 3e6064e45f9a
Revises: 77331afdcd8e
Create Date: 2024-04-17 09:42:42.111657

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e6064e45f9a"
down_revision: Union[str, None] = "77331afdcd8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_proofs_is_public", table_name="proofs", schema="public")
    op.drop_column("proofs", "is_public")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proofs",
        sa.Column(
            "is_public",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index("ix_proofs_is_public", "proofs", ["is_public"], unique=False)
    # ### end Alembic commands ###
