"""Add Product product_quantity_unit field

Revision ID: f657e5ef0a6b
Revises: 7ac630e20d66
Create Date: 2024-02-07 12:07:05.528489

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f657e5ef0a6b"
down_revision: Union[str, None] = "7ac630e20d66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("product_quantity_unit", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "product_quantity_unit")
    # ### end Alembic commands ###
