"""Add Price updated field

Revision ID: 818f9ced20cd
Revises: 58a287bcd336
Create Date: 2024-06-16 11:57:37.751165

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "818f9ced20cd"
down_revision: Union[str, None] = "58a287bcd336"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prices", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "updated")
    # ### end Alembic commands ###
