"""Add Proof location fields

Revision ID: cf78049d89b3
Revises: 49a828f10b05
Create Date: 2024-06-22 22:31:47.195399

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf78049d89b3"
down_revision: Union[str, None] = "49a828f10b05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proofs", sa.Column("location_osm_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "proofs", sa.Column("location_osm_type", sa.String(length=255), nullable=True)
    )
    op.add_column("proofs", sa.Column("location_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "proofs", "locations", ["location_id"], ["id"])
    # Set the location to the location of the first price for each proof
    op.execute(
        """
        UPDATE proofs
        SET location_osm_id = (
            SELECT location_osm_id
            FROM prices
            WHERE prices.proof_id = proofs.id
            LIMIT 1
        )
        WHERE type IN ('PRICE_TAG', 'RECEIPT')
        """
    )
    op.execute(
        """
        UPDATE proofs
        SET location_osm_type = (
            SELECT location_osm_type
            FROM prices
            WHERE prices.proof_id = proofs.id
            LIMIT 1
        )
        WHERE type IN ('PRICE_TAG', 'RECEIPT')
        """
    )
    op.execute(
        """
        UPDATE proofs
        SET location_id = (
            SELECT location_id
            FROM prices
            WHERE prices.proof_id = proofs.id
            LIMIT 1
        )
        WHERE type IN ('PRICE_TAG', 'RECEIPT')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "proofs", type_="foreignkey")
    op.drop_column("proofs", "location_id")
    op.drop_column("proofs", "location_osm_type")
    op.drop_column("proofs", "location_osm_id")
    # ### end Alembic commands ###
