"""Add Proof date field

Revision ID: 5f5835d81917
Revises: 818f9ced20cd
Create Date: 2024-06-17 13:59:42.294690

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f5835d81917"
down_revision: Union[str, None] = "818f9ced20cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proofs", sa.Column("date", sa.Date(), nullable=True))
    # Set the date to the date of the first price for each proof
    op.execute(
        """
        UPDATE proofs
        SET date = (
            SELECT date
            FROM prices
            WHERE prices.proof_id = proofs.id
            LIMIT 1
        )
        WHERE type IN ('PRICE_TAG', 'RECEIPT')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proofs", "date")
    # ### end Alembic commands ###
