"""Add Product categories_tags field

Revision ID: 76d67467ff32
Revises: f657e5ef0a6b
Create Date: 2024-02-09 17:44:53.311432

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76d67467ff32"
down_revision: Union[str, None] = "f657e5ef0a6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "categories_tags",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_products_categories_tags"),
        "products",
        ["categories_tags"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_categories_tags"), table_name="products")
    op.drop_column("products", "categories_tags")
    # ### end Alembic commands ###
