"""Add Proof updated field

Revision ID: 58a287bcd336
Revises: 8ec02f1af257
Create Date: 2024-06-16 11:51:21.584794

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58a287bcd336"
down_revision: Union[str, None] = "8ec02f1af257"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proofs", sa.Column("updated", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proofs", "updated")
    # ### end Alembic commands ###
