"""Add Price source field

Revision ID: 8a6892a20b5d
Revises: 2737db183adb
Create Date: 2024-05-25 20:06:18.409941

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a6892a20b5d"
down_revision: Union[str, None] = "2737db183adb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prices", "source")
    # ### end Alembic commands ###
