"""add_product_categories_tags

Revision ID: 45ebe30cc6af
Revises: f3c157567667
Create Date: 2024-01-30 13:52:17.225079

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45ebe30cc6af"
down_revision: Union[str, None] = "f3c157567667"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "categories_tags",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_products_categories_tags"),
        "products",
        ["categories_tags"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_categories_tags"), table_name="products")
    op.drop_column("products", "categories_tags")
    # ### end Alembic commands ###
