REASON_OTHER = "OTHER"
REASON_LIST = [REASON_OTHER]
REASON_CHOICES = [(key, key) for key in REASON_LIST]

STATUS_OPEN = "OPEN"
STATUS_CLOSED = "CLOSED"
STATUS_LIST = [STATUS_OPEN, STATUS_CLOSED]
STATUS_CHOICES = [(key, key) for key in STATUS_LIST]
