TYPE_PRICE = "PRICE"
TYPE_PROOF = "PROOF"
TYPE_LIST = [TYPE_PRICE, TYPE_PROOF]
TYPE_CHOICES = [(key, key) for key in TYPE_LIST]

REASON_OTHER = "OTHER"
REASON_LIST = [REASON_OTHER]
REASON_CHOICES = [(key, key) for key in REASON_LIST]
