# This is the default OCR configuration of PaddleX, except that
# we decreased max_side_limit to 1200, to speed up OCR processing
pipeline_name: OCR

text_type: general

use_doc_preprocessor: True
use_textline_orientation: True

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    use_doc_orientation_classify: True
    use_doc_unwarping: True
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: null

SubModules:
  TextDetection:
    module_name: text_detection
    box_thresh: 0.6
    limit_side_len: 64
    limit_type: min
    model_dir: null # Replace with the path to your fine-tuned text detection model weights
    model_name: PP-OCRv5_server_det # If the name of the fine-tuned model is different from the default model name, please modify it here as well
    # max_side_limit was decreased from 4000 to 1200
    max_side_limit: 1200
    thresh: 0.3
    unclip_ratio: 1.5
  TextLineOrientation:
    module_name: textline_orientation
    model_name: PP-LCNet_x1_0_textline_ori
    model_dir: null
    batch_size: 6
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv5_server_rec
    model_dir: null
    batch_size: 6
    score_thresh: 0.0
