CHALLENGE_STATUS_UPCOMING = "UPCOMING"
CHALLENGE_STATUS_ONGOING = "ONGOING"
CHALLENGE_STATUS_ARCHIVED = "ARCHIVED"
CHALLENGE_STATUS_LIST = [
    CHALLENGE_STATUS_UPCOMING,
    CHALLENGE_STATUS_ONGOING,
    CHALLENGE_STATUS_ARCHIVED,
]
CHALLENGE_STATUS_CHOICES = [(key, key) for key in CHALLENGE_STATUS_LIST]
