CHALLENGE_STATE_UPCOMING = "Upcoming"
CHALLENGE_STATE_CURRENTLY_RUNNING = "Currently Running"
CHALLENGE_STATE_ARCHIVED = "Archived"
CHALLENGE_STATE_LIST = [
    CHALLENGE_STATE_UPCOMING,
    CHALLENGE_STATE_CURRENTLY_RUNNING,
    CHALLENGE_STATE_ARCHIVED,
]
CHALLENGE_STATE_CHOICES = [(key, key) for key in CHALLENGE_STATE_LIST]
