TYPE_PRICE_TAG = "PRICE_TAG"
TYPE_RECEIPT = "RECEIPT"
TYPE_GDPR_REQUEST = "GDPR_REQUEST"
TYPE_SHOP_IMPORT = "SHOP_IMPORT"

TYPE_LIST = [TYPE_PRICE_TAG, TYPE_RECEIPT, TYPE_GDPR_REQUEST, TYPE_SHOP_IMPORT]
TYPE_CHOICES = [(key, key) for key in TYPE_LIST]

# SINGLE_SHOP: same location, date & currency
TYPE_SINGLE_SHOP_LIST = [TYPE_PRICE_TAG, TYPE_RECEIPT, TYPE_SHOP_IMPORT]
# SHOPPING_SESSION: extra fields
TYPE_SHOPPING_SESSION_LIST = [TYPE_RECEIPT, TYPE_GDPR_REQUEST]
# MULTIPLE_SHOP
TYPE_MULTIPLE_SHOP_LIST = [TYPE_GDPR_REQUEST]
# ALLOW_ANY_USER_PRICE_ADD
TYPE_ALLOW_ANY_USER_PRICE_ADD_LIST = [TYPE_PRICE_TAG]

PROOF_PREDICTION_OBJECT_DETECTION_TYPE = "OBJECT_DETECTION"
PROOF_PREDICTION_CLASSIFICATION_TYPE = "CLASSIFICATION"
PROOF_PREDICTION_RECEIPT_EXTRACTION_TYPE = "RECEIPT_EXTRACTION"
PROOF_PREDICTION_LIST = [
    PROOF_PREDICTION_OBJECT_DETECTION_TYPE,
    PROOF_PREDICTION_CLASSIFICATION_TYPE,
    PROOF_PREDICTION_RECEIPT_EXTRACTION_TYPE,
]

PROOF_TYPE_CHOICES = [(key, key) for key in PROOF_PREDICTION_LIST]

PRICE_TAG_EXTRACTION_TYPE = "PRICE_TAG_EXTRACTION"

PRICE_TAG_PREDICTION_TYPE_CHOICES = [
    (PRICE_TAG_EXTRACTION_TYPE, PRICE_TAG_EXTRACTION_TYPE)
]
