# Generated by Django 5.1 on 2024-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0002_alter_proof_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proof",
            name="type",
            field=models.CharField(
                choices=[
                    ("PRICE_TAG", "PRICE_TAG"),
                    ("RECEIPT", "RECEIPT"),
                    ("GDPR_REQUEST", "GDPR_REQUEST"),
                    ("SHOP_IMPORT", "SHOP_IMPORT"),
                ],
                max_length=20,
            ),
        ),
    ]
