# Generated by Django 5.1 on 2024-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0003_alter_proof_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="image_thumb_path",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proof",
            name="file_path",
            field=models.CharField(blank=True, null=True),
        ),
    ]
