# Generated by Django 5.1 on 2024-10-04 22:36

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0004_proof_image_thumb_path_alter_proof_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="receipt_price_count",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Receipt's number of prices (user input)",
            ),
        ),
        migrations.AddField(
            model_name="proof",
            name="receipt_price_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Receipt's total amount (user input)",
            ),
        ),
    ]
