# Generated by Django 5.1.4 on 2024-12-16 14:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_price_type"),
        ("proofs", "0006_add_proof_prediction_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="When the tag was created in DB",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="When the tag was last updated"
                    ),
                ),
                (
                    "bounding_box",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        size=None,
                        verbose_name="Coordinates of the bounding box, in the format [y_min, x_min, y_max, x_max]",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "deleted"),
                            (1, "linked_to_price"),
                            (2, "not_readable"),
                            (3, "not_price_tag"),
                        ],
                        null=True,
                        verbose_name="The annotation status. Possible values are: - null: not annotated yet- 0 (the price tag was deleted by a user)- 1 (the price tag is linked to a price)- 2 (the price tag barcode or price cannot be read)- 3 (the object is not a price tag)",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        max_length=30,
                        verbose_name="The version of the object detector model that generated the prediction",
                        null=True,
                        blank=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="The name of the user who created this price tag. This field is null if the tag was created by a model.",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="The name of the user who last updated this price tag bounding boxes. If the price tag bounding boxes were never updated, this field is null.",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_tags",
                        to="prices.price",
                        verbose_name="The price linked to this tag",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tags",
                        to="proofs.proof",
                        verbose_name="The proof this price tag belongs to",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Tag",
                "verbose_name_plural": "Price Tags",
                "db_table": "price_tags",
            },
        ),
    ]
