# Generated by Django 5.1 on 2024-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0006_add_proof_prediction_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
