# Generated by Django 5.1.4 on 2025-03-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0013_proof_receipt_online_delivery_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="owner_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
