# Generated by Django 5.1.4 on 2025-03-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0014_proof_owner_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="owner_consumption",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
