# Generated by Django 5.1.4 on 2025-03-23 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0008_price_owner_comment"),
        ("proofs", "0016_pricetag_proof_prediction_remove_pricetag_model_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="The order of the item in the receipt. Item on top is 1."
                    ),
                ),
                (
                    "predicted_data",
                    models.JSONField(
                        default=dict,
                        help_text="A dict representing the predicted data of the receipt item. For example the product name, the price etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[(0, "deleted"), (1, "linked_to_price")],
                        help_text="The current status of the item",
                        null=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the item was created in DB",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When the item was last updated"
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        blank=True,
                        help_text="The price linked to this receipt item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt_items",
                        to="prices.price",
                    ),
                ),
                (
                    "proof",
                    models.ForeignKey(
                        help_text="The proof this receipt item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_items",
                        to="proofs.proof",
                    ),
                ),
                (
                    "proof_prediction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The proof prediction used to create this receipt item. Null if created by a user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt_items",
                        to="proofs.proofprediction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt Item",
                "verbose_name_plural": "Receipt Items",
                "db_table": "receipt_items",
            },
        ),
    ]
