# Generated by Django 5.1.7 on 2025-04-28 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0017_receiptitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
    ]
