# Generated by Django 5.1.7 on 2025-05-08 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0018_proof_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricetag",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
    ]
