# Generated by Django 5.1.4 on 2025-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0019_pricetag_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetag",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "deleted"),
                    (1, "linked_to_price"),
                    (2, "not_readable"),
                    (3, "truncated"),
                    (4, "not_price_tag"),
                    (5, "no_barcode"),
                    (10, "other"),
                ],
                help_text="The annotation status",
                null=True,
            ),
        ),
    ]
