# Generated by Django 5.1.7 on 2025-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0020_alter_pricetag_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricetagprediction",
            name="schema_version",
            field=models.CharField(
                blank=True,
                help_text="The schema version of the prediction data. Used to handle changes in the prediction data structure. It is currently used when calling Gemine API to extract price tags.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricetagprediction",
            name="thought_tokens",
            field=models.TextField(
                blank=True,
                help_text="The thought tokens generated by the model, if available. This is used to provide insights into the model's reasoning process.",
                null=True,
            ),
        ),
    ]
