# Generated by Django 5.1.7 on 2025-08-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("proofs", "0021_pricetagprediction_schema_version_and_more")]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="md5_hash",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name="proof",
            index=models.Index(fields=["md5_hash"], name="proofs_md5_has_ee806d_idx"),
        ),
    ]
