# Generated by Django 5.1.7 on 2025-08-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0021_pricetagprediction_schema_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="image_md5_hash",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
