# Generated by Django 5.1.7 on 2025-09-03 22:01

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0022_proof_image_md5_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proof",
            name="receipt_online_delivery_costs",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Receipt's online delivery costs (user input)",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="receipt_price_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Receipt's total amount (user input)",
            ),
        ),
    ]
