# Generated by Django 5.1.7 on 2025-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0023_alter_proof_receipt_online_delivery_costs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetag",
            name="prediction_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="proof",
            name="prediction_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="proof",
            name="price_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
