# Generated by Django 5.1.13 on 2026-01-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0025_historicalproof"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptitem",
            name="schema_version",
            field=models.CharField(
                blank=True,
                help_text="The schema version of the predicted data. Used to handle changes in the prediction data structure.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricetagprediction",
            name="schema_version",
            field=models.CharField(
                blank=True,
                help_text="The schema version of the prediction data. Used to handle changes in the prediction data structure. It is currently used when calling Gemini API to extract price tags.",
                max_length=20,
                null=True,
            ),
        ),
    ]
