# Generated by Django 5.2.13 on 2026-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0027_alter_historicalproof_currency_alter_proof_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetagprediction",
            name="type",
            field=models.CharField(
                choices=[
                    ("PRICE_TAG_EXTRACTION", "PRICE_TAG_EXTRACTION"),
                    ("PRICE_TAG_CLF", "PRICE_TAG_CLF"),
                ],
                help_text="The type of the prediction",
                max_length=20,
            ),
        ),
    ]
