# Generated by Django 5.2.14 on 2026-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0028_alter_pricetagprediction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproof",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proof",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
