# Generated by Django 5.2.14 on 2026-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofs", "0029_proof_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetagprediction",
            name="type",
            field=models.CharField(
                choices=[
                    ("PRICE_TAG_EXTRACTION", "PRICE_TAG_EXTRACTION"),
                    ("PRICE_TAG_CLF", "PRICE_TAG_CLF"),
                ],
                help_text="The type of the prediction",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="proofprediction",
            name="type",
            field=models.CharField(
                choices=[
                    ("OBJECT_DETECTION", "OBJECT_DETECTION"),
                    ("CLASSIFICATION", "CLASSIFICATION"),
                    ("RECEIPT_EXTRACTION", "RECEIPT_EXTRACTION"),
                    ("RECEIPT_ANONYMIZATION", "RECEIPT_ANONYMIZATION"),
                ],
                max_length=30,
                verbose_name="The type of the prediction",
            ),
        ),
    ]
