# Generated by Django 5.1 on 2024-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[("OSM", "OSM"), ("ONLINE", "ONLINE")],
                default="OSM",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="osm_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="osm_type",
            field=models.CharField(
                blank=True,
                choices=[("NODE", "NODE"), ("WAY", "WAY"), ("RELATION", "RELATION")],
                max_length=10,
                null=True,
            ),
        ),
    ]
