# Generated by Django 5.1 on 2024-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="proof_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
