# Generated by Django 5.1 on 2024-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_location_user_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[("OSM", "OSM"), ("ONLINE", "ONLINE")],
                default="OSM",  # used only for the migration
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="osm_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="osm_type",
            field=models.CharField(
                blank=True,
                choices=[("NODE", "NODE"), ("WAY", "WAY"), ("RELATION", "RELATION")],
                max_length=10,
                null=True,
            ),
        ),
        # Commented to avoid error
        # ValueError: Found wrong number (0) of constraints for locations(osm_id, osm_type)  # noqa
        # migrations.AlterUniqueTogether(
        #     name="location",
        #     unique_together=set(),
        # ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "OSM")),
                fields=("osm_id", "osm_type"),
                name="unique_osm_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "ONLINE")),
                fields=("website_url",),
                name="unique_online_constraint",
            ),
        ),
    ]
