# Generated by Django 5.1 on 2024-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_location_type_website_url_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="source",
            field=models.CharField(blank=True, null=True),
        ),
    ]
