# Generated by Django 5.1.7 on 2025-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0007_alter_location_osm_brand_and_osm_version"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="location",
            name="price_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location",
            name="product_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location",
            name="proof_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location",
            name="user_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
