# Generated by Django 5.2.13 on 2026-04-24 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0008_alter_location_count_default_0"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
    ]
