# Generated by Django 5.1.13 on 2025-11-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_alter_location_count_default_0"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
    ]
