# Generated by Django 5.2.14 on 2026-09-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0009_alter_location_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="osm_version_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
