# Generated by Django 5.2.14 on 2026-06-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0009_alter_location_unique_together"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_osm_constraint",
        ),
        migrations.AddField(
            model_name="location",
            name="osm_version_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "OSM")),
                fields=("osm_id", "osm_type", "osm_version"),
                name="unique_osm_constraint",
            ),
        ),
    ]
