# Generated by Django 5.2.17 on 2026-09-15 08:08

import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0010_location_osm_version_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("OSM", "OSM"), ("ONLINE", "ONLINE")], max_length=20
                    ),
                ),
                ("osm_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "osm_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NODE", "NODE"),
                            ("WAY", "WAY"),
                            ("RELATION", "RELATION"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("osm_name", models.CharField(blank=True, null=True)),
                ("osm_display_name", models.CharField(blank=True, null=True)),
                ("osm_tag_key", models.CharField(blank=True, null=True)),
                ("osm_tag_value", models.CharField(blank=True, null=True)),
                ("osm_brand", models.CharField(blank=True, null=True)),
                ("osm_address_postcode", models.CharField(blank=True, null=True)),
                ("osm_address_city", models.CharField(blank=True, null=True)),
                ("osm_address_country", models.CharField(blank=True, null=True)),
                ("osm_address_country_code", models.CharField(blank=True, null=True)),
                (
                    "osm_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=11, null=True
                    ),
                ),
                (
                    "osm_lon",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=11, null=True
                    ),
                ),
                ("osm_version", models.PositiveIntegerField(blank=True, null=True)),
                ("osm_version_date", models.DateTimeField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("source", models.CharField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_user_id", models.CharField(null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Location",
                "verbose_name_plural": "historical Locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
