# Generated by Django 5.2.17 on 2026-09-22 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0011_historicallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="osm_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="osm_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
    ]
