# Generated by Django 5.1.4 on 2025-02-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_location_type_osm_country_count_and_price_currency_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="price_type_group_community_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="price_type_group_consumption_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
