# Generated by Django 5.1.4 on 2025-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0006_user_price_type_group_community_count_and_price_type_group_consumption_count",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="proof_type_group_community_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="proof_type_group_consumption_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
