# Generated by Django 5.1.4 on 2025-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0007_user_proof_type_group_community_count_and_proof_type_group_consumption_count",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="price_in_proof_owned_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="price_in_proof_not_owned_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
