# Generated by Django 5.1.4 on 2025-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0008_user_price_in_proof_owned_count_and_price_in_proof_not_owned_count_and_price_not_owned_on_proof_owned_count",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="price_not_owned_on_proof_owned_count",
            new_name="price_not_owned_in_proof_owned_count",
        ),
    ]
