# Generated by Django 5.1.7 on 2025-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0009_rename_price_not_owned_on_proof_owned_count_user_price_not_owned_in_proof_owned_count",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="price_type_category_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="price_type_product_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
