# Generated by Django 5.1.7 on 2025-03-23 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_price_type_product_and_category_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="proof_type_group_community_count",
            new_name="proof_kind_community_count",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="proof_type_group_consumption_count",
            new_name="proof_kind_consumption_count",
        ),
    ]
