# Generated by Django 5.1.7 on 2025-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0012_rename_price_type_group_community_count_user_price_kind_community_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="proof_currency_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
