# Generated by Django 5.1.7 on 2025-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_proof_currency_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="proof_currency_count",
            new_name="currency_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="price_currency_count",
        ),
        migrations.AddField(
            model_name="user",
            name="year_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
