# Generated by Django 5.2.14 on 2026-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_user_count_default_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badge_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
