# Generated by Django 5.2.14 on 2026-08-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_badge_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location_type_osm_city_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="proof_type_gdpr_request_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="proof_type_price_tag_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="proof_type_receipt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="proof_type_shop_import_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
