# Generated by Django 5.1 on 2024-09-28 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TotalStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_count", models.PositiveIntegerField(default=0)),
                ("price_barcode_count", models.PositiveIntegerField(default=0)),
                ("price_category_count", models.PositiveIntegerField(default=0)),
                ("product_count", models.PositiveIntegerField(default=0)),
                ("product_with_price_count", models.PositiveIntegerField(default=0)),
                ("location_count", models.PositiveIntegerField(default=0)),
                ("location_with_price_count", models.PositiveIntegerField(default=0)),
                ("proof_count", models.PositiveIntegerField(default=0)),
                ("proof_with_price_count", models.PositiveIntegerField(default=0)),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("user_with_price_count", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Total Stats",
            },
        ),
    ]
