# Generated by Django 5.1 on 2024-10-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="totalstats",
            old_name="price_barcode_count",
            new_name="price_type_product_count",
        ),
        migrations.RenameField(
            model_name="totalstats",
            old_name="price_category_count",
            new_name="price_type_category_count",
        ),
        migrations.AddField(
            model_name="totalstats",
            name="proof_type_price_tag_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="proof_type_receipt_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
