# Generated by Django 5.1.4 on 2024-12-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0003_add_extra_proof_type_and_location_type_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="price_tag_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="price_tag_status_linked_to_price_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="price_tag_status_unknown_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
