# Generated by Django 5.1.4 on 2025-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stats",
            "0006_totalstats_location_type_osm_country_count_and_price_currency_count",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="product_source_obf_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_source_obf_with_price_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_source_off_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_source_off_with_price_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_source_opf_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_source_opf_with_price_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_source_opff_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_source_opff_with_price_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
