# Generated by Django 5.1.4 on 2025-02-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_totalstats_product_count_per_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="price_with_discount_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
