# Generated by Django 5.1.4 on 2025-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0008_totalstats_price_with_discount_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="proof_type_group_community_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="prooft_type_group_consumption_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
