# Generated by Django 5.1.4 on 2025-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stats",
            "0009_totalstats_proof_type_group_community_count_and_type_group_consumption_count",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="totalstats",
            old_name="prooft_type_group_consumption_count",
            new_name="proof_type_group_consumption_count",
        ),
        migrations.AddField(
            model_name="totalstats",
            name="price_type_group_community_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="price_type_group_consumption_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
