# Generated by Django 5.1.4 on 2025-03-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stats",
            "0010_totalstats_price_type_group_community_count_and_price_type_group_consumption_count",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="price_source_api_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="price_source_mobile_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="price_source_other_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="price_source_web_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
