# Generated by Django 5.1.4 on 2025-03-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0011_totalstats_price_count_per_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="proof_source_api_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="proof_source_mobile_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="proof_source_other_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="proof_source_web_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
