# Generated by Django 5.1.4 on 2025-03-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0012_totalstats_proof_count_per_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="price_year_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
