# Generated by Django 5.1.4 on 2025-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0013_totalstats_price_year_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="price_location_country_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
