# Generated by Django 5.1.7 on 2025-03-23 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0014_totalstats_price_location_country_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="totalstats",
            old_name="proof_type_group_community_count",
            new_name="proof_kind_community_count",
        ),
        migrations.RenameField(
            model_name="totalstats",
            old_name="proof_type_group_consumption_count",
            new_name="proof_kind_consumption_count",
        ),
    ]
