# Generated by Django 5.1.7 on 2025-03-23 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0014_totalstats_price_location_country_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="totalstats",
            old_name="price_type_category_tag_count",
            new_name="price_type_category_count",
        ),
        migrations.RenameField(
            model_name="totalstats",
            old_name="price_type_product_code_count",
            new_name="price_type_product_count",
        ),
    ]
