# Generated by Django 5.1.7 on 2025-05-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stats",
            "0016_rename_price_type_group_community_count_totalstats_price_kind_community_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="challenge_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
