# Generated by Django 5.1.7 on 2025-05-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0017_totalstats_challenge_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="price_in_challenge_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="proof_in_challenge_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
