# Generated by Django 5.1.7 on 2025-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0018_totalstats_price_in_challenge_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="proof_currency_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
