# Generated by Django 5.2.14 on 2026-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0019_totalstats_proof_currency_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="product_created_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_created_source_obf_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_created_source_off_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_created_source_opf_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="product_created_source_opff_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
