# Generated by Django 5.2.13 on 2026-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0019_totalstats_proof_currency_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="off_contributions_stats",
            field=models.JSONField(default=dict),
        ),
    ]
