# Generated by Django 5.2.14 on 2026-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0020_totalstats_product_created_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalstats",
            name="badge_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totalstats",
            name="badge_with_user_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
