# Generated by Django 5.1 on 2024-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_location_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
