# Generated by Django 5.1.7 on 2025-05-11 09:59

import openfoodfacts.types
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_location_type_osm_country_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        openfoodfacts.types.Flavor["off"],
                        openfoodfacts.types.Flavor["off"],
                    ),
                    (
                        openfoodfacts.types.Flavor["obf"],
                        openfoodfacts.types.Flavor["obf"],
                    ),
                    (
                        openfoodfacts.types.Flavor["opff"],
                        openfoodfacts.types.Flavor["opff"],
                    ),
                    (
                        openfoodfacts.types.Flavor["opf"],
                        openfoodfacts.types.Flavor["opf"],
                    ),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
