# Generated by Django 5.1.7 on 2025-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_add_fuzzystrmatch_extension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="location_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="location_type_osm_country_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_currency_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="proof_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="user_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
