# Generated by Django 5.1.13 on 2025-11-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_count_default_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
