# Generated by Django 5.1.13 on 2025-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_count_default_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.CharField(blank=True, null=True),
        ),
    ]
