# Generated by Django 5.2.13 on 2026-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="creator",
            field=models.CharField(blank=True, null=True),
        ),
    ]
