name: Run release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-slim
    if: github.repository_owner == 'openfoodfacts'
    steps:
      - uses: googleapis/release-please-action@v5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
